insert into unit(name) VALUES ('JWorks');

insert into employee(username,firstName,lastName,linkedin,email,phoneNumber,function,unit_id,description,gender,birthDate,hireDate,startDate,resignationDate) VALUES ('Nivek','Kevin','Van Houtte','','kevin@gmail.com','047637287','Software Developer Java', 1,'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de 16e eeuw, toen een onbekende drukker een zethaak met letters','MALE','1992-07-25','2015-08-03','2015-11-01',null);
insert into employee(username,firstName,lastName,linkedin,email,phoneNumber,function,unit_id,description,gender,birthDate,hireDate,startDate,resignationDate) VALUES ('Turbots','Dieter','Hubau','','dieter@gmail.com','047637283','Competence Leader Cloud', 1,'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de 16e eeuw, toen een onbekende drukker een zethaak met letters','MALE','1987-04-15','2010-08-03','2010-11-01',null);
insert into employee(username,firstName,lastName,linkedin,email,phoneNumber,function,unit_id,description,gender,birthDate,hireDate,startDate,resignationDate) VALUES ('Gide','Gina','De Beukelaer','','gina@gmail.com','047637283','Software Developer Java', 1,'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de 16e eeuw, toen een onbekende drukker een zethaak met letters','FEMALE','1986-01-23','2016-01-05','2016-03-01',null);
insert into employee(username,firstName,lastName,linkedin,email,phoneNumber,function,unit_id,description,gender,birthDate,hireDate,startDate,resignationDate) VALUES ('Rydg','Ryan','De Gruyter','','ryan@gmail.com','047637283','Software Developer JavaScript', 1,'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de 16e eeuw, toen een onbekende drukker een zethaak met letters','MALE','1987-05-27','2016-01-05','2016-03-01',null);
insert into employee(username,firstName,lastName,linkedin,email,phoneNumber,function,unit_id,description,gender,birthDate,hireDate,startDate,resignationDate) VALUES ('Hami','Hans','Michiels','','hans@gmail.com','047637283','Software Developer Java', 1,'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de 16e eeuw, toen een onbekende drukker een zethaak met letters','MALE','1988-08-28','2010-08-03','2015-08-03',null);
insert into employee(username,firstName,lastName,linkedin,email,phoneNumber,function,unit_id,description,gender,birthDate,hireDate,startDate,resignationDate) VALUES ('Jabi','Jasper','Biesemans','','jasper@gmail.com','047637283','Software Developer JavaScript ', 1,'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de 16e eeuw, toen een onbekende drukker een zethaak met letters','MALE','1993-12-25','2015-08-03','2015-11-01',null);
insert into employee(username,firstName,lastName,linkedin,email,phoneNumber,function,unit_id,description,gender,birthDate,hireDate,startDate,resignationDate) VALUES ('Dedu','Derya','Duru','','derya@gmail.com','047637283','Software Developer Java ', 1,'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de 16e eeuw, toen een onbekende drukker een zethaak met letters','FEMALE','1988-05-25','2010-08-03','2010-11-01',null);
insert into employee(username,firstName,lastName,linkedin,email,phoneNumber,function,unit_id,description,gender,birthDate,hireDate,startDate,resignationDate) VALUES ('joris','Lefever','JLEFE1','','joris.lefever@gmail.com','047637283','Software Developer Java ', 1,'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de 16e eeuw, toen een onbekende drukker een zethaak met letters','MALE','1988-05-25','2010-08-03','2010-11-01',null);

-- Testuser
insert into employee(username,firstName,lastName,linkedin,email,phoneNumber,function,unit_id,description,gender,birthDate,hireDate,startDate,resignationDate) VALUES ('Test','Test','Tester','','test@test.com','04000000000','Software Developer Java ', 1,'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem Ipsum is de standaard proeftekst in deze bedrijfstak sinds de 16e eeuw, toen een onbekende drukker een zethaak met letters','FEMALE','1988-05-25','2010-08-03','2010-11-01',null);

